import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { createTheme, ThemeProvider } from '@mui/material/styles';

import { Poppins } from 'next/font/google'
import Footer from "@/components/layout/Footer";
import { theme } from "@/shared/utility/theme";
import ClientProvider from "./ClientProvider";
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable:'--font-poppins'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={poppins.className}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider theme={theme}>
          <Header />
          <ClientProvider>{children}</ClientProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
